# Site settings
title: Super Rock Games Website
description: Indie Game Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Super Rock Games
user_description: Small indie game developer based in London,UK.
user_title: Indie Game Developer
email: contact@superrockgames.com
twitter_username: SuperRockGames

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
